# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StarWarsConsole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurationid', models.CharField(max_length=1)),
                ('mision', models.CharField(max_length=35)),
                ('bando', models.CharField(max_length=10)),
                ('dificultad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=20)),
                ('mision', models.CharField(max_length=35)),
                ('bando', models.CharField(max_length=10)),
                ('dificultad', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
