# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsConsole', '0002_configuration_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='configurationid',
        ),
    ]
