# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsConsole', '0003_remove_configuration_configurationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='bando',
        ),
        migrations.RemoveField(
            model_name='record',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='record',
            name='mision',
        ),
    ]
